apiVersion: apps/v1
kind: Deployment
metadata:
  name: flisol-demo
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: flisol-demo
        image: quay.io/jvarela01/flisol-demo:8a513285ea85d5c810a5c0618051c80078b398e6