apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: flisol-demo
  app.kubernetes.io/component: flisol-demo
  app.kubernetes.io/instance: flisol-demo
  app.kubernetes.io/part-of: flisol-demo
  app.openshift.io/runtime: quarkus
resources:
- deployment.yaml
- service.yaml
- route.yaml