apiVersion: v1
kind: Service
metadata:
  name: flisol-demo
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/part-of: flisol-demo
    app.openshift.io/runtime: quarkus
    deployment: flisol-demo
  type: ClusterIP